name: Model scheduled release

on:
  schedule:
    - cron: "0 15 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies with apt
        run: |
          apt install swig mecab libmecab-dev mecab-ipadic-utf8
      - name: Install dependencies with pip
        run: |
          python -m pip install -U pip
          pip install aovec
      - name: Run clone
        run: |
          aovec clone && aovec parse && aovec mkvec
      - name: Get date
        run: |
          echo "DATE=$(date +%y%m%d)" >> $GITHUB_ENV
      - name: Rename artifacts
        run: |
          mv *.model aozora_${{ env.DATE }}.model
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.model"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: week${{ env.DATE }}
          artifactErrorsFailBuild: true
