name: Model scheduled release

on:
  schedule:
    - cron: "0 15 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies with apt
        run: |
          sudo apt install swig mecab libmecab-dev mecab-ipadic-utf8 build-essential -y
      - name: Install dependencies with pip
        run: |
          python -m pip install -U pip
          pip install aovec
      - name: Set up neologd
        run: |
          git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd neologd && cd $_
          sudo bin/install-mecab-ipadic-neologd -y
          sudo mv /usr/lib/*/mecab/dic/mecab-ipadic-neologd /var/lib/mecab/dic
          sudo sed -i 's_^dicdir.*_; &\'$'\ndicdir = /var/lib/mecab/dic/mecab-ipadic-neologd_' /etc/mecabrc
      - name: Check MeCab
        run: |
          python src/check_mecab.py 2>/dev/null
      - name: Get date
        run: |
          echo "DATE=$(date +%y%m%d)" >> $GITHUB_ENV
      - name: Clone
        run: |
          aovec clone
      - name: Parse
        run: |
          aovec parse
      - name: Make vecmodel
        run: |
          aovec mkvec -o aozora_week${{ env.DATE }} --both
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.model*,*.npy*,*.kv*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: week${{ env.DATE }}
          artifactErrorsFailBuild: true
